author = "Oxalin"
country_code = "GB"
description = "Airedale & Wharfedale Lines from Leeds to Ilkley, Bradford Forster Square and Skipton, including the busy Shipley triangle"
display_name = "Airedale & Wharfedale Lines (Shipley Triangle)"
doc_files = [ "Airedale_&_Wharfedale_Lines_(Shipley_Triangle).md",]
factual = true
img_files = [ "Airedale_&_Wharfedale_Lines_(Shipley_Triangle).bmp",]
name = "Airedale & Wharfedale Lines (Shipley Triangle)"
release_date = "2023-07-08"
rly_file = "Airedale_&_Wharfedale_Lines_(Shipley_Triangle).rly"
ssn_files = [ "Airedale_&_Wharfedale_Lines_(Shipley_Triangle)_Initial_Session.ssn",]
ttb_files = [ "Airedale_&_Wharfedale_Lines_(Shipley_Triangle)_06-09-23.ttb",]
version = "1.0.0"
year = 2023
signal_position = "left"
contributors = []
